name: love-game
version: '0.0.3'
summary: A LÖVE Game
description: |
  A sample LÖVE Game.

confinement: strict
grade: stable

apps:
  love-game:
    command: bin/love.wrapper
    plugs:
      - network
      - network-bind
      - opengl
      - pulseaudio
      - x11

parts:
  love:
    plugin: dump
    source: https://bitbucket.org/rude/love/downloads/love_0.10.2ppa1_amd64.deb
  liblove:
    plugin: dump
    source: https://bitbucket.org/rude/love/downloads/liblove0_0.10.2ppa1_amd64.deb
  game:
    plugin: make
    source: .
    stage-packages:
      - libdevil1c2
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglew1.13
      - libilmbase12
      - libluajit-5.1-2
      - libmodplug1
      - libmpg123-0
      - libogg0
      - libopenal1
      - libphysfs1
      - libsdl2-2.0-0
      - libtheora0
      - libvorbisfile3
      - lua-socket
  wrapper:
    plugin: dump
    source: ./assets/snap
    organize:
      'love.wrapper': 'bin/love.wrapper'
